CREATE SCHEMA IF NOT EXISTS passive_secretary;

CREATE TABLE IF NOT EXISTS passive_secretary.business_connections (
    tenant_id TEXT NOT NULL,
    tenant_owner_id BIGINT NOT NULL,
    source_id TEXT NOT NULL,
    test_run_id TEXT NOT NULL DEFAULT '',
    business_connection_id TEXT NOT NULL,
    owner_telegram_user_id BIGINT NOT NULL,
    owner_ref TEXT NOT NULL,
    user_chat_id BIGINT,
    enabled BOOLEAN NOT NULL,
    observed_can_reply BOOLEAN NOT NULL DEFAULT FALSE,
    connection_date TIMESTAMPTZ NOT NULL,
    last_update_id BIGINT NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (tenant_id, tenant_owner_id, source_id, test_run_id, business_connection_id)
);

ALTER TABLE passive_secretary.business_connections
    ADD COLUMN IF NOT EXISTS last_update_id BIGINT NOT NULL DEFAULT 0;

-- Upgrade legacy receive-only installations in place.  CREATE TABLE IF NOT
-- EXISTS does not add columns to an already deployed table, while archive.py
-- writes this observation on every Business connection update.
ALTER TABLE passive_secretary.business_connections
    ADD COLUMN IF NOT EXISTS observed_can_reply BOOLEAN NOT NULL DEFAULT FALSE;

CREATE TABLE IF NOT EXISTS passive_secretary.messages (
    tenant_id TEXT NOT NULL,
    tenant_owner_id BIGINT NOT NULL,
    source_id TEXT NOT NULL,
    test_run_id TEXT NOT NULL DEFAULT '',
    chat_id BIGINT NOT NULL,
    message_id BIGINT NOT NULL,
    business_connection_id TEXT NOT NULL,
    source_ref TEXT NOT NULL,
    chat_label TEXT NOT NULL,
    message_ref TEXT NOT NULL,
    reply_to_message_id BIGINT,
    reply_to_message_ref TEXT,
    media_group_id TEXT,
    media_group_ref TEXT,
    sender_telegram_user_id BIGINT,
    sender_ref TEXT NOT NULL,
    sender_label TEXT NOT NULL,
    direction TEXT NOT NULL CHECK (direction IN ('incoming', 'outgoing')),
    body TEXT,
    caption TEXT,
    content_kind TEXT NOT NULL,
    attachment JSONB NOT NULL DEFAULT '{}'::jsonb,
    sent_at TIMESTAMPTZ,
    edited_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    ingest_origin TEXT NOT NULL DEFAULT 'business_update'
        CHECK (ingest_origin IN ('business_update', 'group_update', 'history_backfill')),
    last_update_id BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (tenant_id, tenant_owner_id, source_id, test_run_id, chat_id, message_id)
);

ALTER TABLE passive_secretary.messages
    ADD COLUMN IF NOT EXISTS last_update_id BIGINT NOT NULL DEFAULT 0;
ALTER TABLE passive_secretary.messages
    ADD COLUMN IF NOT EXISTS ingest_origin TEXT NOT NULL DEFAULT 'business_update';

-- Older deployments created an inline CHECK without a stable name. Replace
-- only the known column-level constraint so group_update can be introduced
-- without weakening the origin allowlist.
DO $$
DECLARE constraint_name TEXT;
BEGIN
    SELECT con.conname INTO constraint_name
    FROM pg_constraint AS con
    JOIN pg_class AS rel ON rel.oid=con.conrelid
    JOIN pg_namespace AS ns ON ns.oid=rel.relnamespace
    WHERE ns.nspname='passive_secretary'
      AND rel.relname='messages'
      AND con.contype='c'
      AND pg_get_constraintdef(con.oid) LIKE '%ingest_origin%'
    LIMIT 1;
    IF constraint_name IS NOT NULL THEN
        EXECUTE format(
            'ALTER TABLE passive_secretary.messages DROP CONSTRAINT %I',
            constraint_name
        );
    END IF;
END $$;
ALTER TABLE passive_secretary.messages
    ADD CONSTRAINT messages_ingest_origin_check
    CHECK (ingest_origin IN ('business_update', 'group_update', 'history_backfill'));

-- Nullable metadata columns make this upgrade safe for existing archives.
-- Raw Telegram relation identifiers remain storage-only; retrieval exposes
-- only the keyed opaque references generated by the normalizer.
ALTER TABLE passive_secretary.messages
    ADD COLUMN IF NOT EXISTS reply_to_message_id BIGINT;
ALTER TABLE passive_secretary.messages
    ADD COLUMN IF NOT EXISTS reply_to_message_ref TEXT;
ALTER TABLE passive_secretary.messages
    ADD COLUMN IF NOT EXISTS media_group_id TEXT;
ALTER TABLE passive_secretary.messages
    ADD COLUMN IF NOT EXISTS media_group_ref TEXT;

CREATE INDEX IF NOT EXISTS messages_scope_sent_idx
    ON passive_secretary.messages
    (tenant_id, tenant_owner_id, source_id, test_run_id, sent_at DESC);
CREATE INDEX IF NOT EXISTS messages_source_ref_idx
    ON passive_secretary.messages
    (tenant_id, tenant_owner_id, source_id, test_run_id, source_ref, sent_at DESC);
CREATE INDEX IF NOT EXISTS messages_message_ref_idx
    ON passive_secretary.messages
    (tenant_id, tenant_owner_id, source_id, test_run_id, message_ref);

CREATE TABLE IF NOT EXISTS passive_secretary.media_enrichments (
    tenant_id TEXT NOT NULL,
    tenant_owner_id BIGINT NOT NULL,
    source_id TEXT NOT NULL,
    test_run_id TEXT NOT NULL DEFAULT '',
    chat_id BIGINT NOT NULL,
    message_id BIGINT NOT NULL,
    media_index INTEGER NOT NULL CHECK (media_index BETWEEN 0 AND 7),
    business_connection_id TEXT NOT NULL,
    file_unique_id TEXT NOT NULL,
    job_id TEXT NOT NULL,
    media_kind TEXT NOT NULL CHECK (media_kind IN ('voice', 'video_note', 'document')),
    status TEXT NOT NULL CHECK (
        status IN (
            'transcribed', 'unsupported', 'too_large',
            'download_failed_permanent', 'asr_failed_permanent'
        )
    ),
    transcript TEXT,
    language TEXT,
    content_sha256 TEXT,
    actual_bytes BIGINT,
    duration_ms BIGINT,
    processor_service TEXT NOT NULL,
    processor_version TEXT NOT NULL,
    processor_engine TEXT NOT NULL,
    processor_model TEXT NOT NULL,
    processor_quantization TEXT NOT NULL,
    source_update_id BIGINT NOT NULL,
    received_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (
        tenant_id, tenant_owner_id, source_id, test_run_id,
        chat_id, message_id, media_index, processor_version
    ),
    UNIQUE (tenant_id, tenant_owner_id, source_id, test_run_id, job_id),
    FOREIGN KEY (tenant_id, tenant_owner_id, source_id, test_run_id, chat_id, message_id)
        REFERENCES passive_secretary.messages
        (tenant_id, tenant_owner_id, source_id, test_run_id, chat_id, message_id)
        ON DELETE CASCADE,
    CHECK (
        (status='transcribed' AND transcript IS NOT NULL)
        OR (status<>'transcribed' AND transcript IS NULL AND language IS NULL)
    ),
    CHECK (actual_bytes IS NULL OR actual_bytes BETWEEN 0 AND 20971520),
    CHECK (duration_ms IS NULL OR duration_ms BETWEEN 0 AND 1800000)
);

CREATE INDEX IF NOT EXISTS media_enrichments_message_idx
    ON passive_secretary.media_enrichments
    (tenant_id, tenant_owner_id, source_id, test_run_id, chat_id, message_id, media_index);

CREATE TABLE IF NOT EXISTS passive_secretary.outbound_intents (
    tenant_id TEXT NOT NULL,
    tenant_owner_id BIGINT NOT NULL,
    source_id TEXT NOT NULL,
    test_run_id TEXT NOT NULL DEFAULT '',
    intent_id TEXT NOT NULL,
    session_ref TEXT NOT NULL,
    source_ref TEXT NOT NULL,
    message_hmac TEXT NOT NULL,
    chat_id BIGINT NOT NULL,
    business_connection_id TEXT NOT NULL,
    anchor_message_id BIGINT NOT NULL,
    reply_message_id BIGINT,
    status TEXT NOT NULL CHECK (
        status IN (
            'prepared', 'sending', 'sent', 'denied', 'failed_known', 'ambiguous'
        )
    ),
    expires_at TIMESTAMPTZ NOT NULL,
    telegram_message_id BIGINT,
    failure_code TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (
        tenant_id, tenant_owner_id, source_id, test_run_id, intent_id
    ),
    CHECK (telegram_message_id IS NULL OR telegram_message_id > 0),
    CHECK (anchor_message_id > 0),
    CHECK (reply_message_id IS NULL OR reply_message_id > 0)
);

CREATE INDEX IF NOT EXISTS outbound_intents_scope_status_idx
    ON passive_secretary.outbound_intents
    (tenant_id, tenant_owner_id, source_id, test_run_id, status, updated_at DESC);
CREATE INDEX IF NOT EXISTS outbound_intents_payload_anchor_idx
    ON passive_secretary.outbound_intents
    (tenant_id, tenant_owner_id, source_id, test_run_id,
     source_ref, message_hmac, anchor_message_id, created_at DESC);

CREATE TABLE IF NOT EXISTS passive_secretary.message_versions (
    id BIGSERIAL PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    tenant_owner_id BIGINT NOT NULL,
    source_id TEXT NOT NULL,
    test_run_id TEXT NOT NULL DEFAULT '',
    chat_id BIGINT NOT NULL,
    message_id BIGINT NOT NULL,
    version_observed_at TIMESTAMPTZ NOT NULL,
    body TEXT,
    caption TEXT,
    attachment JSONB NOT NULL DEFAULT '{}'::jsonb,
    FOREIGN KEY (tenant_id, tenant_owner_id, source_id, test_run_id, chat_id, message_id)
        REFERENCES passive_secretary.messages
        (tenant_id, tenant_owner_id, source_id, test_run_id, chat_id, message_id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS passive_secretary.archive_events (
    event_key TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    tenant_owner_id BIGINT NOT NULL,
    source_id TEXT NOT NULL,
    test_run_id TEXT NOT NULL DEFAULT '',
    kind TEXT NOT NULL,
    update_id BIGINT NOT NULL,
    received_at TIMESTAMPTZ NOT NULL,
    processed_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS archive_events_scope_received_idx
    ON passive_secretary.archive_events
    (tenant_id, tenant_owner_id, source_id, test_run_id, received_at DESC);
