#!/usr/bin/env python3
"""Очистка метаданных офисных файлов после генерации.

Вешается на hook post_tool_call. Проходит по свежим (за последние 15 минут)
файлам .docx/.xlsx/.pptx в рабочем каталоге и приводит docProps/core.xml
к виду обычного документа: убирает «generated by python-docx», ставит
реальные даты и автора. Ничего не печатает в stdout (протокол хука).
"""
import os, re, shutil, sys, tempfile, time, zipfile
from datetime import datetime, timezone

WORKSPACE = os.environ.get("HERMES_DOC_WORKSPACE", "")
AUTHOR = os.environ.get("HERMES_DOC_AUTHOR", "")
EXTS = (".docx", ".xlsx", ".pptx")
FRESH_SECONDS = 15 * 60

def now_iso():
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

def clean_core_xml(xml: str) -> str:
    stamp = now_iso()
    # описание/комментарии — вычистить полностью
    xml = re.sub(r"<dc:description>.*?</dc:description>", "<dc:description></dc:description>", xml, flags=re.S)
    xml = re.sub(r"<cp:keywords>.*?</cp:keywords>", lambda m: m.group(0), xml, flags=re.S)
    # автор и правивший (только если задан HERMES_DOC_AUTHOR)
    if AUTHOR:
        xml = re.sub(r"<dc:creator>.*?</dc:creator>", "<dc:creator>%s</dc:creator>" % AUTHOR, xml, flags=re.S)
    if AUTHOR and "<cp:lastModifiedBy" in xml:
        xml = re.sub(r"<cp:lastModifiedBy\s*/>", "<cp:lastModifiedBy>%s</cp:lastModifiedBy>" % AUTHOR, xml)
        xml = re.sub(r"<cp:lastModifiedBy>.*?</cp:lastModifiedBy>",
                     "<cp:lastModifiedBy>%s</cp:lastModifiedBy>" % AUTHOR, xml, flags=re.S)
    # даты — реальные
    for tag in ("dcterms:created", "dcterms:modified"):
        xml = re.sub(r"<%s[^>]*>.*?</%s>" % (tag, tag),
                     '<%s xsi:type="dcterms:W3CDTF">%s</%s>' % (tag, stamp, tag), xml, flags=re.S)
    return xml

def process(path: str) -> bool:
    try:
        with zipfile.ZipFile(path) as z:
            names = z.namelist()
            if "docProps/core.xml" not in names:
                return False
            core = z.read("docProps/core.xml").decode("utf-8", "ignore")
            if "python-docx" not in core and "2013-12-23" not in core:
                return False
            items = [(n, z.read(n)) for n in names]
    except Exception:
        return False

    new_core = clean_core_xml(core).encode("utf-8")
    fd, tmp = tempfile.mkstemp(dir=os.path.dirname(path), suffix=".tmp")
    os.close(fd)
    try:
        with zipfile.ZipFile(tmp, "w", zipfile.ZIP_DEFLATED) as out:
            for name, data in items:
                out.writestr(name, new_core if name == "docProps/core.xml" else data)
        st = os.stat(path)
        shutil.move(tmp, path)
        os.chown(path, st.st_uid, st.st_gid)
        os.chmod(path, st.st_mode & 0o7777)
        return True
    except Exception:
        if os.path.exists(tmp):
            os.unlink(tmp)
        return False

def main():
    try:
        sys.stdin.read()
    except Exception:
        pass
    if not WORKSPACE or not os.path.isdir(WORKSPACE):
        return  # HERMES_DOC_WORKSPACE не задан — хук выключен
    cutoff = time.time() - FRESH_SECONDS
    for root, _dirs, files in os.walk(WORKSPACE):
        for fn in files:
            if not fn.lower().endswith(EXTS):
                continue
            p = os.path.join(root, fn)
            try:
                if os.path.getmtime(p) < cutoff:
                    continue
            except OSError:
                continue
            process(p)

if __name__ == "__main__":
    main()
